# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'geekbrains-Nagibator3000' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "Koloda"
  pod "Toast-Swift"
  # Pods for geekbrains-Nagibator3000

end
